### ISSUE TITLE
Manque les fichiers .mid !

### ISSUE THREAD

**Issue by philippebarbosa** [ldrolez/free-midi-chords#2]
Hello !
Juste pour info, il manque l'export des fichiers .mid dans la toute dernière release ! ;)
Merci pour ce taf en tout cas, très utile merci !!
@barbomusic

**Comment by ldrolez** [comment]
Hello! Les fichiers MIDI sont dans le zip. Les deux autres fichiers contiennent juste le code source pour générer les accords ;)

**Comment by philippebarbosa** [comment]
AH yes, merci ! Étrange j'ai le souvenir d'avoir regardé les 3 dossiers dans la dernière release, mais bon j'ai du me planter ;) Merci !
