### ISSUE TITLE
add drum pattern beats too

### ISSUE THREAD

**Issue by RustoMCSpit** [ldrolez/free-midi-chords#20]

**Comment by RustoMCSpit** [comment]
https://mobilemusicpro.com/collections/free-downloads some stuff here

**Comment by RustoMCSpit** [comment]
https://splice.com/blog/how-to-make-drum-patterns/
https://splice.com/blog/wp-content/uploads/2019/10/MIDI-Drum-Patterns.zip

**Comment by RustoMCSpit** [comment]
> Thanks for the suggestion but many DAWs already have drum patterns built-in... anyway I prefer to create another project for this, because chord progressions are generated by a script and this drum patterns not

wait so will you make a drum pattern project???

**Comment by RustoMCSpit** [comment]
https://github.com/Fannon/midi-chords-and-scales-pack/issues/2 

heres a list of stuff

**Comment by kenwud** [comment]
i can see that this topic is pretty much settled but id love a repository for drum pattern midis, i could try compiling or help compile

**Comment by RustoMCSpit** [comment]
> i can see that this topic is pretty much settled but id love a repository for drum pattern midis, i could try compiling or help compile

any update on this?

**Comment by RustoMCSpit** [comment]
> Thanks for the suggestion but many DAWs already have drum patterns built-in... anyway I prefer to create another project for this, because chord progressions are generated by a script and this drum patterns not

any update on this?

**Comment by RustoMCSpit** [comment]
any updates?

**Comment by kenwud** [comment]
sorrry i havent been very well lately. the link rusto left does have a collection of about 15 styles of drum patterns. 
my issue is that i dont feel very creative, and i pretty much resort to either a 4 on the floor beat, or a dubstep type beat and i always feel like it is very boring or generic. even though i gladly listen to music using the same patterns, when i do it it seems boring

**Comment by RustoMCSpit** [comment]
> sorrry i havent been very well lately. the link rusto left does have a collection of about 15 styles of drum patterns. my issue is that i dont feel very creative, and i pretty much resort to either a 4 on the floor beat, or a dubstep type beat and i always feel like it is very boring or generic. even though i gladly listen to music using the same patterns, when i do it it seems boring

oh dont worry about that, as long as there is a gpl 3 repo where any musician can merge their patterns into in an organised fashion (time signatures + genre?) it will be great! you dont even need to make your own. it makes sense though to be a twin project of this one so if idrolez wants to do it thatd be cool. if worse comes to wear i can try to figure it out

**Comment by RustoMCSpit** [comment]
update
?

**Comment by kenwud** [comment]
following. FL studio FPC plugin comes with a pretty decentl selection of pretty generic midi patterns that are not in midi format that could serve as a good starting point though

**Comment by RustoMCSpit** [comment]
@ldrolez will you take forks of drum beats?

**Comment by ldrolez** [comment]
I think this should be part of another side project, no time currently...
