### ISSUE TITLE
Chord Progression Suggestions

### ISSUE THREAD

**Issue by 180Rotator** [ldrolez/free-midi-chords#6]
1. I7-V7(inv. 2)-VImadd9-IV7
2. VI-V-IV-V-IIm-V-I
3.VI-VII-V-VI-IV#dim(inv. 1)-V(inv. 2)

**Comment by ldrolez** [comment]
Hi! I'm adding your suggestions for the next release, but currently 'python mingus' is not able to output progressions with 'add9' chords only '9th'... I'll have to patch mingus, add9 chords are a must!

**Comment by ldrolez** [comment]
https://github.com/bspaans/python-mingus/pull/87

**Comment by RustoMCSpit** [comment]
> Hi! I'm adding your suggestions for the next release, but currently 'python mingus' is not able to output progressions with 'add9' chords only '9th'... I'll have to patch mingus, add9 chords are a must!

update?

**Comment by ldrolez** [comment]
The next release will have the VIadd9 chord, I had to fork Python-Mingus.

**Comment by RustoMCSpit** [comment]
> The next release will have the VIadd9 chord, I had to fork Python-Mingus.

https://github.com/edudobay

if you can find them on social media all you have to do is tell them.to merge the stuff on the repo honestly

**Comment by RustoMCSpit** [comment]
https://www.youtube.com/c/EduardoDobay

thats their name and youtube

**Comment by ldrolez** [comment]
> > The next release will have the VIadd9 chord, I had to fork Python-Mingus.
> 
> https://github.com/edudobay
> 
> if you can find them on social media all you have to do is tell them.to merge the stuff on the repo honestly

There is no more dev on their repo since 3 years 😉

**Comment by RustoMCSpit** [comment]
> > > The next release will have the VIadd9 chord, I had to fork Python-Mingus.
> > 
> > 
> > https://github.com/edudobay
> > if you can find them on social media all you have to do is tell them.to merge the stuff on the repo honestly
> 
> There is no more dev on their repo since 3 years 😉

yeah but theyve had activity in september on other repos so they xould easily merge it

**Comment by RustoMCSpit** [comment]
> > > The next release will have the VIadd9 chord, I had to fork Python-Mingus.
> > 
> > 
> > https://github.com/edudobay
> > if you can find them on social media all you have to do is tell them.to merge the stuff on the repo honestly
> 
> There is no more dev on their repo since 3 years 😉

https://twitter.com/samg7b9
heres the other
